docs(setup): including ci config

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,24 +1,88 @@
-# Use the latest 2.1 version of CircleCI pipeline process engine.
-# See: https://circleci.com/docs/2.0/configuration-reference
-version: 2.1
-
-# Define a job to be invoked later in a workflow.
-# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
+version: 2
 jobs:
-  build:
-    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
-    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
+  checkout_code:
     docker:
       - image: circleci/node
-    # Add steps to the job
-    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
+
     steps:
       - checkout
-      - run: npm run test:ci
+      - restore_cache:
+          keys:
+          - v1-dependencies-{{ checksum "package.json" }}
+      - run: yarn
+      - save_cache:
+          paths:
+            - node_modules
+          key: v1-dependencies-{{ checksum "package.json" }}
+      - persist_to_workspace:
+          root: .
+          paths:
+            - node_modules
 
-# Invoke jobs via workflows
-# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
+  precompile:
+    docker:
+      - image: circleci/node
+
+    steps:
+      - checkout
+      - attach_workspace:
+          at: .
+      - run: yarn build
+      - persist_to_workspace:
+          root: .
+          paths:
+            - build
+  deploy:
+    machine: true
+
+    steps:
+      - attach_workspace:
+          at: .
+      - deploy:
+          name: Deploy to GitHub Pages
+          command: |
+              set -e
+              if [ ! -d "build" ]
+              then
+                  echo "build folder not found"
+                  exit 1
+              fi
+              mkdir gh-pages-branch
+              cd gh-pages-branch
+              git config --global user.email "$GH_EMAIL" > /dev/null 2>&1
+              git config --global user.name "$GH_NAME" > /dev/null 2>&1
+              git init
+              git remote add --fetch origin https://${GH_TOKEN}@github.com/vicentelyrio/vite-template.git
+              if git rev-parse --verify origin/gh-pages > /dev/null 2>&1
+              then
+                  git checkout gh-pages
+                  git rm -rf .
+              else
+                  git checkout --orphan gh-pages
+              fi
+              cp -a "../build/." .
+              git add -A
+              git commit --allow-empty -m "Deploy to GitHub pages [ci skip]"
+              git push --force --quiet origin gh-pages > /dev/null 2>&1
+              cd ..
+              rm -rf gh-pages-branch
+              echo "Finished GitHub pages Deployment!"
 workflows:
-  build-workflow:
+  version: 2
+  build-and-deploy:
     jobs:
-      - build
+      - checkout_code:
+          filters:
+            branches:
+              ignore:
+                - gh-pages
+      - precompile:
+          requires:
+            - checkout_code
+      - deploy:
+          requires:
+            - precompile
+          filters:
+            branches:
+              only:
+                - main
